### ISSUE TITLE
你好，请问如何与您取得联系（Hello, how to contact you?）

### ISSUE THREAD

**Issue by luckysmg** [CosynPa/RevealSpringAnimation#1]
我们在另一个开源项目中想要使用您的源代码，但是注意到此项目并没有放licence 文件，所以想与您确认是否允许

We want to use your source code in another open source project, but notice that this project does not release the licence file, so we want to confirm with you whether it is allowed

**Comment by CoolDude53** [comment]
@CosynPa also interested in this
